### PR TITLE
fix: Ensure tests clean up their caches.

### LINKED ISSUE #119: Make sure tests clean up after themselves
- [x] Use a unique cache name.
- [x] Delete the cache at the end of the test
  - [ ] Ideally whether or not the test is cancelled.

### PR DESCRIPTION
**Pull request by schwern**
Close #119

### CODE REVIEW

File: momento/simple_cache_client_test.go [hunk 1]
```diff
@@ -103,7 +103,7 @@ func TestBasicHappyPathSDKFlow(t *testing.T) {
 		t.Error(fmt.Errorf("error occurred deleting cache=%s err=%+v", randomCacheName, err))
 	}
 
-	cleanUpClient(client)
+	teardown(client, cacheName, randomCacheName)
```
Comment (eaddingtonwhite) [inline momento/simple_cache_client_test.go:106]: should we put this up top w/ a defer maybe?
`defer teardown(client, cacheName, randomCacheName)`

**Review by eaddingtonwhite — DISMISSED** [review]

**Review by eaddingtonwhite — APPROVED** [review]
